// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens 
WHERE user_id = $1 AND device_id = $2
`

type DeleteDeviceTokenParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID string      `db:"device_id" json:"device_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.UserID, arg.DeviceID)
	return err
}

const getDeviceTokenByDeviceID = `-- name: GetDeviceTokenByDeviceID :one
SELECT id, user_id, device_id, push_token, platform, app_version, created_at, updated_at FROM device_tokens
WHERE user_id = $1 AND device_id = $2
`

type GetDeviceTokenByDeviceIDParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID string      `db:"device_id" json:"device_id"`
}

func (q *Queries) GetDeviceTokenByDeviceID(ctx context.Context, arg GetDeviceTokenByDeviceIDParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByDeviceID, arg.UserID, arg.DeviceID)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.PushToken,
		&i.Platform,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTokensByUser = `-- name: GetDeviceTokensByUser :many
SELECT id, user_id, device_id, push_token, platform, app_version, created_at, updated_at FROM device_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDeviceTokensByUser(ctx context.Context, userID pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.PushToken,
			&i.Platform,
			&i.AppVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (user_id, device_id, push_token, platform, app_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, device_id) 
DO UPDATE SET 
    push_token = EXCLUDED.push_token,
    platform = EXCLUDED.platform,
    app_version = EXCLUDED.app_version,
    updated_at = NOW()
RETURNING id, user_id, device_id, push_token, platform, app_version, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID   string      `db:"device_id" json:"device_id"`
	PushToken  string      `db:"push_token" json:"push_token"`
	Platform   string      `db:"platform" json:"platform"`
	AppVersion *string     `db:"app_version" json:"app_version"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken,
		arg.UserID,
		arg.DeviceID,
		arg.PushToken,
		arg.Platform,
		arg.AppVersion,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.PushToken,
		&i.Platform,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
