// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDriverActiveShipmentCount = `-- name: GetDriverActiveShipmentCount :one
SELECT COUNT(*) FROM shipments 
WHERE driver_id = $1 
  AND tenant_id = $2 
  AND status IN ('assigned', 'in_transit', 'delayed', 'arrived')
`

type GetDriverActiveShipmentCountParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDriverActiveShipmentCount(ctx context.Context, arg GetDriverActiveShipmentCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDriverActiveShipmentCount, arg.DriverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriverDeliveriesThisMonth = `-- name: GetDriverDeliveriesThisMonth :one
SELECT COUNT(*) FROM shipments 
WHERE driver_id = $1 
  AND tenant_id = $2 
  AND status = 'delivered' 
  AND actual_delivery >= DATE_TRUNC('month', NOW())
`

type GetDriverDeliveriesThisMonthParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDriverDeliveriesThisMonth(ctx context.Context, arg GetDriverDeliveriesThisMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDriverDeliveriesThisMonth, arg.DriverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriverDeliveriesThisWeek = `-- name: GetDriverDeliveriesThisWeek :one
SELECT COUNT(*) FROM shipments 
WHERE driver_id = $1 
  AND tenant_id = $2 
  AND status = 'delivered' 
  AND actual_delivery >= DATE_TRUNC('week', NOW())
`

type GetDriverDeliveriesThisWeekParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDriverDeliveriesThisWeek(ctx context.Context, arg GetDriverDeliveriesThisWeekParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDriverDeliveriesThisWeek, arg.DriverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriverDeliveriesToday = `-- name: GetDriverDeliveriesToday :one
SELECT COUNT(*) FROM shipments 
WHERE driver_id = $1 
  AND tenant_id = $2 
  AND status = 'delivered' 
  AND actual_delivery >= DATE_TRUNC('day', NOW())
`

type GetDriverDeliveriesTodayParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDriverDeliveriesToday(ctx context.Context, arg GetDriverDeliveriesTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDriverDeliveriesToday, arg.DriverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriverTotalDeliveries = `-- name: GetDriverTotalDeliveries :one
SELECT COUNT(*) FROM shipments 
WHERE driver_id = $1 
  AND tenant_id = $2 
  AND status = 'delivered'
`

type GetDriverTotalDeliveriesParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDriverTotalDeliveries(ctx context.Context, arg GetDriverTotalDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDriverTotalDeliveries, arg.DriverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriverVehicleAssignment = `-- name: GetDriverVehicleAssignment :one
SELECT v.id, v.tenant_id, v.plate_number, v.vehicle_type, v.is_active, v.created_at, v.updated_at
FROM vehicles v
INNER JOIN shipments s ON s.vehicle_id = v.id
WHERE s.driver_id = $1 
  AND s.tenant_id = $2 
  AND s.status IN ('assigned', 'in_transit', 'delayed', 'arrived')
LIMIT 1
`

type GetDriverVehicleAssignmentParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDriverVehicleAssignment(ctx context.Context, arg GetDriverVehicleAssignmentParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getDriverVehicleAssignment, arg.DriverID, arg.TenantID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlateNumber,
		&i.VehicleType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
