// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Action     string             `db:"action" json:"action"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID        `db:"entity_id" json:"entity_id"`
	OldValue   []byte             `db:"old_value" json:"old_value"`
	NewValue   []byte             `db:"new_value" json:"new_value"`
	IpAddress  *string            `db:"ip_address" json:"ip_address"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProofOfDelivery struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID             pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID               pgtype.UUID        `db:"driver_id" json:"driver_id"`
	RecipientName          string             `db:"recipient_name" json:"recipient_name"`
	RecipientPhone         *string            `db:"recipient_phone" json:"recipient_phone"`
	SignatureData          *string            `db:"signature_data" json:"signature_data"`
	SignatureUrl           *string            `db:"signature_url" json:"signature_url"`
	PhotoUrls              []string           `db:"photo_urls" json:"photo_urls"`
	DeliveryAddress        *string            `db:"delivery_address" json:"delivery_address"`
	DeliveryCoordinates    interface{}        `db:"delivery_coordinates" json:"delivery_coordinates"`
	DeliveryNotes          *string            `db:"delivery_notes" json:"delivery_notes"`
	LocationVerified       *bool              `db:"location_verified" json:"location_verified"`
	LocationMismatchMeters pgtype.Numeric     `db:"location_mismatch_meters" json:"location_mismatch_meters"`
	RecordedAt             pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt               pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
}

type Session struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	DeviceID         *string            `db:"device_id" json:"device_id"`
	UserAgent        *string            `db:"user_agent" json:"user_agent"`
	IpAddress        *string            `db:"ip_address" json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type Shipment struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TrackingNumber         string             `db:"tracking_number" json:"tracking_number"`
	OriginAddress          string             `db:"origin_address" json:"origin_address"`
	OriginCoordinates      interface{}        `db:"origin_coordinates" json:"origin_coordinates"`
	DestinationAddress     string             `db:"destination_address" json:"destination_address"`
	DestinationCoordinates interface{}        `db:"destination_coordinates" json:"destination_coordinates"`
	CustomerName           string             `db:"customer_name" json:"customer_name"`
	CustomerPhone          string             `db:"customer_phone" json:"customer_phone"`
	CargoDescription       *string            `db:"cargo_description" json:"cargo_description"`
	CargoWeight            pgtype.Numeric     `db:"cargo_weight" json:"cargo_weight"`
	CargoValue             pgtype.Numeric     `db:"cargo_value" json:"cargo_value"`
	SpecialInstructions    *string            `db:"special_instructions" json:"special_instructions"`
	DriverID               pgtype.UUID        `db:"driver_id" json:"driver_id"`
	VehicleID              pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	Status                 string             `db:"status" json:"status"`
	StatusNote             *string            `db:"status_note" json:"status_note"`
	StatusReason           *string            `db:"status_reason" json:"status_reason"`
	EstimatedDelivery      pgtype.Timestamptz `db:"estimated_delivery" json:"estimated_delivery"`
	ActualDelivery         pgtype.Timestamptz `db:"actual_delivery" json:"actual_delivery"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy              pgtype.UUID        `db:"created_by" json:"created_by"`
}

type SyncMetadatum struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	DriverID         pgtype.UUID        `db:"driver_id" json:"driver_id"`
	LastSyncAt       pgtype.Timestamptz `db:"last_sync_at" json:"last_sync_at"`
	LastEventID      pgtype.UUID        `db:"last_event_id" json:"last_event_id"`
	PendingSyncCount *int32             `db:"pending_sync_count" json:"pending_sync_count"`
	StorageUsedKb    *int32             `db:"storage_used_kb" json:"storage_used_kb"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Slug       string             `db:"slug" json:"slug"`
	Plan       string             `db:"plan" json:"plan"`
	MaxDrivers *int32             `db:"max_drivers" json:"max_drivers"`
	IsActive   *bool              `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TrackingEvent struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID     pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID       pgtype.UUID        `db:"driver_id" json:"driver_id"`
	Coordinates    interface{}        `db:"coordinates" json:"coordinates"`
	AccuracyMeters pgtype.Numeric     `db:"accuracy_meters" json:"accuracy_meters"`
	SpeedKph       pgtype.Numeric     `db:"speed_kph" json:"speed_kph"`
	Heading        pgtype.Numeric     `db:"heading" json:"heading"`
	EventType      string             `db:"event_type" json:"event_type"`
	Status         *string            `db:"status" json:"status"`
	Note           *string            `db:"note" json:"note"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt       pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
	DeviceID       *string            `db:"device_id" json:"device_id"`
	BatteryLevel   *int32             `db:"battery_level" json:"battery_level"`
}

type User struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	TenantID              pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Role                  string             `db:"role" json:"role"`
	FullName              string             `db:"full_name" json:"full_name"`
	Phone                 *string            `db:"phone" json:"phone"`
	Email                 *string            `db:"email" json:"email"`
	PasswordHash          *string            `db:"password_hash" json:"password_hash"`
	PinHash               *string            `db:"pin_hash" json:"pin_hash"`
	IsActive              *bool              `db:"is_active" json:"is_active"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FailedLoginAttempts   *int32             `db:"failed_login_attempts" json:"failed_login_attempts"`
	LockedUntil           pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	PasswordResetRequired *bool              `db:"password_reset_required" json:"password_reset_required"`
}

type Vehicle struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	PlateNumber string             `db:"plate_number" json:"plate_number"`
	VehicleType *string            `db:"vehicle_type" json:"vehicle_type"`
	IsActive    *bool              `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
