// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPOD = `-- name: CreatePOD :one
INSERT INTO proof_of_deliveries (
    tenant_id, shipment_id, driver_id,
    recipient_name, recipient_phone,
    signature_data, signature_url, photo_urls,
    delivery_address, delivery_coordinates,
    delivery_notes, location_verified, location_mismatch_meters,
    recorded_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 
    ST_MakePoint($10, $11)::geometry(Point, 4326),
    $12, $13, $14, $15
) RETURNING id, tenant_id, shipment_id, driver_id, recipient_name, recipient_phone, signature_data, signature_url, photo_urls, delivery_address, delivery_coordinates, delivery_notes, location_verified, location_mismatch_meters, recorded_at, synced_at
`

type CreatePODParams struct {
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID             pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID               pgtype.UUID        `db:"driver_id" json:"driver_id"`
	RecipientName          string             `db:"recipient_name" json:"recipient_name"`
	RecipientPhone         *string            `db:"recipient_phone" json:"recipient_phone"`
	SignatureData          *string            `db:"signature_data" json:"signature_data"`
	SignatureUrl           *string            `db:"signature_url" json:"signature_url"`
	PhotoUrls              []string           `db:"photo_urls" json:"photo_urls"`
	DeliveryAddress        *string            `db:"delivery_address" json:"delivery_address"`
	StMakepoint            interface{}        `db:"st_makepoint" json:"st_makepoint"`
	StMakepoint_2          interface{}        `db:"st_makepoint_2" json:"st_makepoint_2"`
	DeliveryNotes          *string            `db:"delivery_notes" json:"delivery_notes"`
	LocationVerified       *bool              `db:"location_verified" json:"location_verified"`
	LocationMismatchMeters pgtype.Numeric     `db:"location_mismatch_meters" json:"location_mismatch_meters"`
	RecordedAt             pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) CreatePOD(ctx context.Context, arg CreatePODParams) (ProofOfDelivery, error) {
	row := q.db.QueryRow(ctx, createPOD,
		arg.TenantID,
		arg.ShipmentID,
		arg.DriverID,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.SignatureData,
		arg.SignatureUrl,
		arg.PhotoUrls,
		arg.DeliveryAddress,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.DeliveryNotes,
		arg.LocationVerified,
		arg.LocationMismatchMeters,
		arg.RecordedAt,
	)
	var i ProofOfDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentID,
		&i.DriverID,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.SignatureData,
		&i.SignatureUrl,
		&i.PhotoUrls,
		&i.DeliveryAddress,
		&i.DeliveryCoordinates,
		&i.DeliveryNotes,
		&i.LocationVerified,
		&i.LocationMismatchMeters,
		&i.RecordedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getPODByShipmentID = `-- name: GetPODByShipmentID :one
SELECT id, tenant_id, shipment_id, driver_id,
       recipient_name, recipient_phone,
       signature_data, signature_url, photo_urls,
       delivery_address,
       ST_X(delivery_coordinates::geometry) as delivery_longitude,
       ST_Y(delivery_coordinates::geometry) as delivery_latitude,
       delivery_notes, location_verified, location_mismatch_meters,
       recorded_at, synced_at
FROM proof_of_deliveries
WHERE shipment_id = $1 AND tenant_id = $2
`

type GetPODByShipmentIDParams struct {
	ShipmentID pgtype.UUID `db:"shipment_id" json:"shipment_id"`
	TenantID   pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

type GetPODByShipmentIDRow struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID             pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID               pgtype.UUID        `db:"driver_id" json:"driver_id"`
	RecipientName          string             `db:"recipient_name" json:"recipient_name"`
	RecipientPhone         *string            `db:"recipient_phone" json:"recipient_phone"`
	SignatureData          *string            `db:"signature_data" json:"signature_data"`
	SignatureUrl           *string            `db:"signature_url" json:"signature_url"`
	PhotoUrls              []string           `db:"photo_urls" json:"photo_urls"`
	DeliveryAddress        *string            `db:"delivery_address" json:"delivery_address"`
	DeliveryLongitude      interface{}        `db:"delivery_longitude" json:"delivery_longitude"`
	DeliveryLatitude       interface{}        `db:"delivery_latitude" json:"delivery_latitude"`
	DeliveryNotes          *string            `db:"delivery_notes" json:"delivery_notes"`
	LocationVerified       *bool              `db:"location_verified" json:"location_verified"`
	LocationMismatchMeters pgtype.Numeric     `db:"location_mismatch_meters" json:"location_mismatch_meters"`
	RecordedAt             pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt               pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
}

func (q *Queries) GetPODByShipmentID(ctx context.Context, arg GetPODByShipmentIDParams) (GetPODByShipmentIDRow, error) {
	row := q.db.QueryRow(ctx, getPODByShipmentID, arg.ShipmentID, arg.TenantID)
	var i GetPODByShipmentIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentID,
		&i.DriverID,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.SignatureData,
		&i.SignatureUrl,
		&i.PhotoUrls,
		&i.DeliveryAddress,
		&i.DeliveryLongitude,
		&i.DeliveryLatitude,
		&i.DeliveryNotes,
		&i.LocationVerified,
		&i.LocationMismatchMeters,
		&i.RecordedAt,
		&i.SyncedAt,
	)
	return i, err
}

const getUnsyncedPODs = `-- name: GetUnsyncedPODs :many
SELECT id, tenant_id, shipment_id, driver_id,
       recipient_name, recipient_phone,
       signature_data, signature_url, photo_urls,
       delivery_address,
       ST_X(delivery_coordinates::geometry) as delivery_longitude,
       ST_Y(delivery_coordinates::geometry) as delivery_latitude,
       delivery_notes, location_verified, location_mismatch_meters,
       recorded_at, synced_at
FROM proof_of_deliveries
WHERE driver_id = $1 AND tenant_id = $2 AND synced_at IS NULL
ORDER BY recorded_at ASC
`

type GetUnsyncedPODsParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

type GetUnsyncedPODsRow struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID             pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID               pgtype.UUID        `db:"driver_id" json:"driver_id"`
	RecipientName          string             `db:"recipient_name" json:"recipient_name"`
	RecipientPhone         *string            `db:"recipient_phone" json:"recipient_phone"`
	SignatureData          *string            `db:"signature_data" json:"signature_data"`
	SignatureUrl           *string            `db:"signature_url" json:"signature_url"`
	PhotoUrls              []string           `db:"photo_urls" json:"photo_urls"`
	DeliveryAddress        *string            `db:"delivery_address" json:"delivery_address"`
	DeliveryLongitude      interface{}        `db:"delivery_longitude" json:"delivery_longitude"`
	DeliveryLatitude       interface{}        `db:"delivery_latitude" json:"delivery_latitude"`
	DeliveryNotes          *string            `db:"delivery_notes" json:"delivery_notes"`
	LocationVerified       *bool              `db:"location_verified" json:"location_verified"`
	LocationMismatchMeters pgtype.Numeric     `db:"location_mismatch_meters" json:"location_mismatch_meters"`
	RecordedAt             pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt               pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
}

func (q *Queries) GetUnsyncedPODs(ctx context.Context, arg GetUnsyncedPODsParams) ([]GetUnsyncedPODsRow, error) {
	rows, err := q.db.Query(ctx, getUnsyncedPODs, arg.DriverID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnsyncedPODsRow{}
	for rows.Next() {
		var i GetUnsyncedPODsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShipmentID,
			&i.DriverID,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.SignatureData,
			&i.SignatureUrl,
			&i.PhotoUrls,
			&i.DeliveryAddress,
			&i.DeliveryLongitude,
			&i.DeliveryLatitude,
			&i.DeliveryNotes,
			&i.LocationVerified,
			&i.LocationMismatchMeters,
			&i.RecordedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePODSyncedAt = `-- name: UpdatePODSyncedAt :exec
UPDATE proof_of_deliveries
SET synced_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePODSyncedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updatePODSyncedAt, id)
	return err
}
