// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvancedSearchShipments(ctx context.Context, arg AdvancedSearchShipmentsParams) ([]Shipment, error)
	AssignDriverToShipment(ctx context.Context, arg AssignDriverToShipmentParams) (Shipment, error)
	CancelShipment(ctx context.Context, arg CancelShipmentParams) (Shipment, error)
	CountActiveSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountActiveShipmentsByTenant(ctx context.Context, arg CountActiveShipmentsByTenantParams) (int64, error)
	CountDeliveriesToday(ctx context.Context, arg CountDeliveriesTodayParams) (int64, error)
	CountDriversByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountDriversWithActiveShipments(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountShipmentsByStatus(ctx context.Context, arg CountShipmentsByStatusParams) (int64, error)
	CountShipmentsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountTrackingEventsByShipment(ctx context.Context, shipmentID pgtype.UUID) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountVehiclesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreatePOD(ctx context.Context, arg CreatePODParams) (ProofOfDelivery, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTrackingEvent(ctx context.Context, arg CreateTrackingEventParams) (TrackingEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) error
	GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetDashboardActivity(ctx context.Context, arg GetDashboardActivityParams) ([]Shipment, error)
	GetDashboardAlerts(ctx context.Context, arg GetDashboardAlertsParams) ([]Shipment, error)
	GetDeviceTokenByDeviceID(ctx context.Context, arg GetDeviceTokenByDeviceIDParams) (DeviceToken, error)
	GetDeviceTokensByUser(ctx context.Context, userID pgtype.UUID) ([]DeviceToken, error)
	GetDriverActiveShipmentCount(ctx context.Context, arg GetDriverActiveShipmentCountParams) (int64, error)
	GetDriverDeliveriesThisMonth(ctx context.Context, arg GetDriverDeliveriesThisMonthParams) (int64, error)
	GetDriverDeliveriesThisWeek(ctx context.Context, arg GetDriverDeliveriesThisWeekParams) (int64, error)
	GetDriverDeliveriesToday(ctx context.Context, arg GetDriverDeliveriesTodayParams) (int64, error)
	GetDriverTotalDeliveries(ctx context.Context, arg GetDriverTotalDeliveriesParams) (int64, error)
	GetDriverVehicleAssignment(ctx context.Context, arg GetDriverVehicleAssignmentParams) (Vehicle, error)
	GetLatestDriverLocations(ctx context.Context, tenantID pgtype.UUID) ([]GetLatestDriverLocationsRow, error)
	GetPODByShipmentID(ctx context.Context, arg GetPODByShipmentIDParams) (GetPODByShipmentIDRow, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetShipmentByID(ctx context.Context, arg GetShipmentByIDParams) (Shipment, error)
	GetShipmentByTrackingNumber(ctx context.Context, trackingNumber string) (Shipment, error)
	GetShipmentsForSync(ctx context.Context, arg GetShipmentsForSyncParams) ([]Shipment, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTrackingEventsForSync(ctx context.Context, arg GetTrackingEventsForSyncParams) ([]GetTrackingEventsForSyncRow, error)
	GetUnsyncedPODs(ctx context.Context, arg GetUnsyncedPODsParams) ([]GetUnsyncedPODsRow, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByEmailAndTenant(ctx context.Context, arg GetUserByEmailAndTenantParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	GetUserByPhoneAndTenant(ctx context.Context, arg GetUserByPhoneAndTenantParams) (User, error)
	GetVehicleByID(ctx context.Context, arg GetVehicleByIDParams) (Vehicle, error)
	HardDeleteVehicle(ctx context.Context, arg HardDeleteVehicleParams) error
	IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) (User, error)
	ListActiveSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	ListActiveShipmentsByDriver(ctx context.Context, arg ListActiveShipmentsByDriverParams) ([]Shipment, error)
	ListActiveVehiclesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Vehicle, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAuditLogsByTenant(ctx context.Context, arg ListAuditLogsByTenantParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListDriversByTenant(ctx context.Context, arg ListDriversByTenantParams) ([]User, error)
	ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	ListShipmentsByDriver(ctx context.Context, arg ListShipmentsByDriverParams) ([]Shipment, error)
	ListShipmentsByStatus(ctx context.Context, arg ListShipmentsByStatusParams) ([]Shipment, error)
	ListShipmentsByTenant(ctx context.Context, arg ListShipmentsByTenantParams) ([]Shipment, error)
	ListTrackingEventsByDriver(ctx context.Context, arg ListTrackingEventsByDriverParams) ([]ListTrackingEventsByDriverRow, error)
	ListTrackingEventsByShipment(ctx context.Context, arg ListTrackingEventsByShipmentParams) ([]ListTrackingEventsByShipmentRow, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error)
	ListVehiclesByTenant(ctx context.Context, arg ListVehiclesByTenantParams) ([]Vehicle, error)
	LockUserAccount(ctx context.Context, arg LockUserAccountParams) error
	MarkTrackingEventsSynced(ctx context.Context, dollar_1 []pgtype.UUID) error
	ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	RevokeSessionByUser(ctx context.Context, arg RevokeSessionByUserParams) error
	SearchShipments(ctx context.Context, arg SearchShipmentsParams) ([]Shipment, error)
	UnlockUserAccount(ctx context.Context, id pgtype.UUID) error
	UpdatePIN(ctx context.Context, arg UpdatePINParams) (User, error)
	UpdatePODSyncedAt(ctx context.Context, id pgtype.UUID) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error)
	// actual_delivery is stamped the first time a shipment reaches 'delivered' and
	// preserved thereafter, so a re-sent status update cannot move the timestamp.
	// The driver stats and delivery-count queries read this column.
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
}

var _ Querier = (*Queries)(nil)
