// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessionsByUser = `-- name: CountActiveSessionsByUser :one
SELECT COUNT(*) FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountActiveSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at, created_at, revoked_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	DeviceID         *string            `db:"device_id" json:"device_id"`
	UserAgent        *string            `db:"user_agent" json:"user_agent"`
	IpAddress        *string            `db:"ip_address" json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TenantID,
		arg.RefreshTokenHash,
		arg.DeviceID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at, created_at, revoked_at FROM sessions 
WHERE refresh_token_hash = $1 
  AND revoked_at IS NULL 
  AND expires_at > NOW()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at, created_at, revoked_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at, created_at, revoked_at FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at, created_at, revoked_at FROM sessions
WHERE user_id = $1 
  AND revoked_at IS NULL 
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.RefreshTokenHash,
			&i.DeviceID,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, tenant_id, refresh_token_hash, device_id, user_agent, ip_address, expires_at, created_at, revoked_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.RefreshTokenHash,
			&i.DeviceID,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND id != $2 AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.UserID, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByUser = `-- name: RevokeSessionByUser :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1 AND user_id = $2
`

type RevokeSessionByUserParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeSessionByUser(ctx context.Context, arg RevokeSessionByUserParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByUser, arg.ID, arg.UserID)
	return err
}
