// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advancedSearchShipments = `-- name: AdvancedSearchShipments :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR driver_id = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
  AND ($6::text IS NULL OR origin_address ILIKE '%' || $6 || '%')
  AND ($7::text IS NULL OR destination_address ILIKE '%' || $7 || '%')
  AND ($8::text IS NULL OR tracking_number ILIKE '%' || $8 || '%'
       OR customer_name ILIKE '%' || $8 || '%'
       OR customer_phone ILIKE '%' || $8 || '%')
ORDER BY created_at DESC
LIMIT $9 OFFSET $10
`

type AdvancedSearchShipmentsParams struct {
	TenantID pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Column2  string             `db:"column_2" json:"column_2"`
	Column3  pgtype.UUID        `db:"column_3" json:"column_3"`
	Column4  pgtype.Timestamptz `db:"column_4" json:"column_4"`
	Column5  pgtype.Timestamptz `db:"column_5" json:"column_5"`
	Column6  string             `db:"column_6" json:"column_6"`
	Column7  string             `db:"column_7" json:"column_7"`
	Column8  string             `db:"column_8" json:"column_8"`
	Limit    int32              `db:"limit" json:"limit"`
	Offset   int32              `db:"offset" json:"offset"`
}

func (q *Queries) AdvancedSearchShipments(ctx context.Context, arg AdvancedSearchShipmentsParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, advancedSearchShipments,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assignDriverToShipment = `-- name: AssignDriverToShipment :one
UPDATE shipments
SET driver_id = $1, status = 'assigned', updated_at = NOW()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by
`

type AssignDriverToShipmentParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) AssignDriverToShipment(ctx context.Context, arg AssignDriverToShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, assignDriverToShipment, arg.DriverID, arg.ID, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const cancelShipment = `-- name: CancelShipment :one
UPDATE shipments
SET status = 'cancelled', status_reason = $2, updated_at = NOW()
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by
`

type CancelShipmentParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	StatusReason *string     `db:"status_reason" json:"status_reason"`
	TenantID     pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) CancelShipment(ctx context.Context, arg CancelShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, cancelShipment, arg.ID, arg.StatusReason, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const countActiveShipmentsByTenant = `-- name: CountActiveShipmentsByTenant :one
SELECT COUNT(*) FROM shipments 
WHERE tenant_id = $1 
  AND status = ANY($2::text[])
`

type CountActiveShipmentsByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Column2  []string    `db:"column_2" json:"column_2"`
}

func (q *Queries) CountActiveShipmentsByTenant(ctx context.Context, arg CountActiveShipmentsByTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveShipmentsByTenant, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveriesToday = `-- name: CountDeliveriesToday :one
SELECT COUNT(*) FROM shipments 
WHERE tenant_id = $1 
  AND status = 'delivered' 
  AND actual_delivery >= $2
`

type CountDeliveriesTodayParams struct {
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ActualDelivery pgtype.Timestamptz `db:"actual_delivery" json:"actual_delivery"`
}

func (q *Queries) CountDeliveriesToday(ctx context.Context, arg CountDeliveriesTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveriesToday, arg.TenantID, arg.ActualDelivery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipmentsByStatus = `-- name: CountShipmentsByStatus :one
SELECT COUNT(*) FROM shipments 
WHERE tenant_id = $1 AND status = $2
`

type CountShipmentsByStatusParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Status   string      `db:"status" json:"status"`
}

func (q *Queries) CountShipmentsByStatus(ctx context.Context, arg CountShipmentsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShipmentsByStatus, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipmentsByTenant = `-- name: CountShipmentsByTenant :one
SELECT COUNT(*) FROM shipments WHERE tenant_id = $1
`

func (q *Queries) CountShipmentsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShipmentsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (
    tenant_id, tracking_number,
    origin_address,
    destination_address,
    customer_name, customer_phone,
    cargo_description, cargo_weight, cargo_value, special_instructions,
    driver_id, vehicle_id,
    status, status_note,
    estimated_delivery,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by
`

type CreateShipmentParams struct {
	TenantID            pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TrackingNumber      string             `db:"tracking_number" json:"tracking_number"`
	OriginAddress       string             `db:"origin_address" json:"origin_address"`
	DestinationAddress  string             `db:"destination_address" json:"destination_address"`
	CustomerName        string             `db:"customer_name" json:"customer_name"`
	CustomerPhone       string             `db:"customer_phone" json:"customer_phone"`
	CargoDescription    *string            `db:"cargo_description" json:"cargo_description"`
	CargoWeight         pgtype.Numeric     `db:"cargo_weight" json:"cargo_weight"`
	CargoValue          pgtype.Numeric     `db:"cargo_value" json:"cargo_value"`
	SpecialInstructions *string            `db:"special_instructions" json:"special_instructions"`
	DriverID            pgtype.UUID        `db:"driver_id" json:"driver_id"`
	VehicleID           pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	Status              string             `db:"status" json:"status"`
	StatusNote          *string            `db:"status_note" json:"status_note"`
	EstimatedDelivery   pgtype.Timestamptz `db:"estimated_delivery" json:"estimated_delivery"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.TenantID,
		arg.TrackingNumber,
		arg.OriginAddress,
		arg.DestinationAddress,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CargoDescription,
		arg.CargoWeight,
		arg.CargoValue,
		arg.SpecialInstructions,
		arg.DriverID,
		arg.VehicleID,
		arg.Status,
		arg.StatusNote,
		arg.EstimatedDelivery,
		arg.CreatedBy,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDashboardActivity = `-- name: GetDashboardActivity :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tenant_id = $1
ORDER BY updated_at DESC
LIMIT $2
`

type GetDashboardActivityParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) GetDashboardActivity(ctx context.Context, arg GetDashboardActivityParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, getDashboardActivity, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardAlerts = `-- name: GetDashboardAlerts :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tenant_id = $1
  AND status IN ('issue', 'delayed')
ORDER BY updated_at DESC
LIMIT $2
`

type GetDashboardAlertsParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
}

func (q *Queries) GetDashboardAlerts(ctx context.Context, arg GetDashboardAlertsParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, getDashboardAlerts, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShipmentByID = `-- name: GetShipmentByID :one
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE id = $1 AND tenant_id = $2
`

type GetShipmentByIDParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetShipmentByID(ctx context.Context, arg GetShipmentByIDParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByID, arg.ID, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getShipmentByTrackingNumber = `-- name: GetShipmentByTrackingNumber :one
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tracking_number = $1
`

func (q *Queries) GetShipmentByTrackingNumber(ctx context.Context, trackingNumber string) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByTrackingNumber, trackingNumber)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getShipmentsForSync = `-- name: GetShipmentsForSync :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE driver_id = $1
  AND tenant_id = $2
  AND (
    status IN ('assigned', 'in_transit', 'delayed', 'arrived')
    OR $3::timestamptz IS NULL
    OR updated_at > $3::timestamptz
  )
ORDER BY created_at DESC
`

type GetShipmentsForSyncParams struct {
	DriverID  pgtype.UUID        `db:"driver_id" json:"driver_id"`
	TenantID  pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// A NULL cursor means the client has never synced, so there is no lower bound
// and everything assigned to the driver is returned. Without the explicit NULL
// check, "updated_at > NULL" evaluates to NULL rather than true, and a first
// sync silently pulled only shipments already in an active status.
func (q *Queries) GetShipmentsForSync(ctx context.Context, arg GetShipmentsForSyncParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, getShipmentsForSync, arg.DriverID, arg.TenantID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveShipmentsByDriver = `-- name: ListActiveShipmentsByDriver :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE driver_id = $1 
  AND tenant_id = $2
  AND status IN ('assigned', 'in_transit', 'delayed', 'arrived')
ORDER BY created_at DESC
`

type ListActiveShipmentsByDriverParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ListActiveShipmentsByDriver(ctx context.Context, arg ListActiveShipmentsByDriverParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listActiveShipmentsByDriver, arg.DriverID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentsByDriver = `-- name: ListShipmentsByDriver :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE driver_id = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListShipmentsByDriverParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListShipmentsByDriver(ctx context.Context, arg ListShipmentsByDriverParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listShipmentsByDriver,
		arg.DriverID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentsByStatus = `-- name: ListShipmentsByStatus :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListShipmentsByStatusParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Status   string      `db:"status" json:"status"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListShipmentsByStatus(ctx context.Context, arg ListShipmentsByStatusParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listShipmentsByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentsByTenant = `-- name: ListShipmentsByTenant :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListShipmentsByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListShipmentsByTenant(ctx context.Context, arg ListShipmentsByTenantParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listShipmentsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShipments = `-- name: SearchShipments :many
SELECT id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by FROM shipments
WHERE tenant_id = $1
  AND (
    tracking_number ILIKE '%' || $2 || '%'
    OR customer_name ILIKE '%' || $2 || '%'
    OR customer_phone ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchShipmentsParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Column2  *string     `db:"column_2" json:"column_2"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchShipments(ctx context.Context, arg SearchShipmentsParams) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, searchShipments,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TrackingNumber,
			&i.OriginAddress,
			&i.OriginCoordinates,
			&i.DestinationAddress,
			&i.DestinationCoordinates,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CargoDescription,
			&i.CargoWeight,
			&i.CargoValue,
			&i.SpecialInstructions,
			&i.DriverID,
			&i.VehicleID,
			&i.Status,
			&i.StatusNote,
			&i.StatusReason,
			&i.EstimatedDelivery,
			&i.ActualDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipment = `-- name: UpdateShipment :one
UPDATE shipments
SET
    origin_address = COALESCE($3, origin_address),
    destination_address = COALESCE($4, destination_address),
    customer_name = COALESCE($5, customer_name),
    customer_phone = COALESCE($6, customer_phone),
    cargo_description = COALESCE($7, cargo_description),
    cargo_weight = COALESCE($8, cargo_weight),
    cargo_value = COALESCE($9, cargo_value),
    special_instructions = COALESCE($10, special_instructions),
    driver_id = COALESCE($11, driver_id),
    vehicle_id = COALESCE($12, vehicle_id),
    status = COALESCE($13, status),
    status_note = COALESCE($14, status_note),
    status_reason = COALESCE($15, status_reason),
    estimated_delivery = COALESCE($16, estimated_delivery),
    actual_delivery = COALESCE($17, actual_delivery)
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by
`

type UpdateShipmentParams struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	TenantID            pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	OriginAddress       *string            `db:"origin_address" json:"origin_address"`
	DestinationAddress  *string            `db:"destination_address" json:"destination_address"`
	CustomerName        *string            `db:"customer_name" json:"customer_name"`
	CustomerPhone       *string            `db:"customer_phone" json:"customer_phone"`
	CargoDescription    *string            `db:"cargo_description" json:"cargo_description"`
	CargoWeight         pgtype.Numeric     `db:"cargo_weight" json:"cargo_weight"`
	CargoValue          pgtype.Numeric     `db:"cargo_value" json:"cargo_value"`
	SpecialInstructions *string            `db:"special_instructions" json:"special_instructions"`
	DriverID            pgtype.UUID        `db:"driver_id" json:"driver_id"`
	VehicleID           pgtype.UUID        `db:"vehicle_id" json:"vehicle_id"`
	Status              *string            `db:"status" json:"status"`
	StatusNote          *string            `db:"status_note" json:"status_note"`
	StatusReason        *string            `db:"status_reason" json:"status_reason"`
	EstimatedDelivery   pgtype.Timestamptz `db:"estimated_delivery" json:"estimated_delivery"`
	ActualDelivery      pgtype.Timestamptz `db:"actual_delivery" json:"actual_delivery"`
}

func (q *Queries) UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipment,
		arg.ID,
		arg.TenantID,
		arg.OriginAddress,
		arg.DestinationAddress,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CargoDescription,
		arg.CargoWeight,
		arg.CargoValue,
		arg.SpecialInstructions,
		arg.DriverID,
		arg.VehicleID,
		arg.Status,
		arg.StatusNote,
		arg.StatusReason,
		arg.EstimatedDelivery,
		arg.ActualDelivery,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :one
UPDATE shipments
SET status = $1,
    status_note = $2,
    status_reason = $3,
    actual_delivery = CASE
        WHEN $1 = 'delivered' THEN COALESCE(actual_delivery, NOW())
        ELSE actual_delivery
    END,
    updated_at = NOW()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, tracking_number, origin_address, origin_coordinates, destination_address, destination_coordinates, customer_name, customer_phone, cargo_description, cargo_weight, cargo_value, special_instructions, driver_id, vehicle_id, status, status_note, status_reason, estimated_delivery, actual_delivery, created_at, updated_at, created_by
`

type UpdateShipmentStatusParams struct {
	Status       string      `db:"status" json:"status"`
	StatusNote   *string     `db:"status_note" json:"status_note"`
	StatusReason *string     `db:"status_reason" json:"status_reason"`
	ID           pgtype.UUID `db:"id" json:"id"`
	TenantID     pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

// actual_delivery is stamped the first time a shipment reaches 'delivered' and
// preserved thereafter, so a re-sent status update cannot move the timestamp.
// The driver stats and delivery-count queries read this column.
func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipmentStatus,
		arg.Status,
		arg.StatusNote,
		arg.StatusReason,
		arg.ID,
		arg.TenantID,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TrackingNumber,
		&i.OriginAddress,
		&i.OriginCoordinates,
		&i.DestinationAddress,
		&i.DestinationCoordinates,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CargoDescription,
		&i.CargoWeight,
		&i.CargoValue,
		&i.SpecialInstructions,
		&i.DriverID,
		&i.VehicleID,
		&i.Status,
		&i.StatusNote,
		&i.StatusReason,
		&i.EstimatedDelivery,
		&i.ActualDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
