// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, plan, max_drivers)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, plan, max_drivers, is_active, created_at, updated_at
`

type CreateTenantParams struct {
	Name       string `db:"name" json:"name"`
	Slug       string `db:"slug" json:"slug"`
	Plan       string `db:"plan" json:"plan"`
	MaxDrivers *int32 `db:"max_drivers" json:"max_drivers"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.MaxDrivers,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxDrivers,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, plan, max_drivers, is_active, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxDrivers,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, plan, max_drivers, is_active, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxDrivers,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    name = COALESCE($2, name),
    plan = COALESCE($3, plan),
    max_drivers = COALESCE($4, max_drivers),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, name, slug, plan, max_drivers, is_active, created_at, updated_at
`

type UpdateTenantParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	Name       *string     `db:"name" json:"name"`
	Plan       *string     `db:"plan" json:"plan"`
	MaxDrivers *int32      `db:"max_drivers" json:"max_drivers"`
	IsActive   *bool       `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Plan,
		arg.MaxDrivers,
		arg.IsActive,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxDrivers,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
