// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDriversByTenant = `-- name: CountDriversByTenant :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1 AND role = 'driver' AND is_active = true
`

func (q *Queries) CountDriversByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDriversByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDriversWithActiveShipments = `-- name: CountDriversWithActiveShipments :one
SELECT COUNT(DISTINCT s.driver_id) 
FROM shipments s
INNER JOIN users u ON s.driver_id = u.id
WHERE s.tenant_id = $1 
  AND s.status IN ('assigned', 'in_transit', 'delayed', 'arrived')
  AND u.is_active = true
`

func (q *Queries) CountDriversWithActiveShipments(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDriversWithActiveShipments, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByTenant = `-- name: CountUsersByTenant :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1 AND is_active = true
`

func (q *Queries) CountUsersByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required
`

type CreateUserParams struct {
	TenantID     pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Role         string      `db:"role" json:"role"`
	FullName     string      `db:"full_name" json:"full_name"`
	Phone        *string     `db:"phone" json:"phone"`
	Email        *string     `db:"email" json:"email"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
	PinHash      *string     `db:"pin_hash" json:"pin_hash"`
	IsActive     *bool       `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Role,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.PinHash,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET is_active = false
WHERE id = $1 AND tenant_id = $2
`

type DeleteUserParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.TenantID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const getUserByEmailAndTenant = `-- name: GetUserByEmailAndTenant :one
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE email = $1 AND tenant_id = $2
`

type GetUserByEmailAndTenantParams struct {
	Email    *string     `db:"email" json:"email"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByEmailAndTenant(ctx context.Context, arg GetUserByEmailAndTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndTenant, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE id = $1 AND tenant_id = $2
`

type GetUserByIDParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const getUserByPhoneAndTenant = `-- name: GetUserByPhoneAndTenant :one
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE phone = $1 AND tenant_id = $2
`

type GetUserByPhoneAndTenantParams struct {
	Phone    *string     `db:"phone" json:"phone"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByPhoneAndTenant(ctx context.Context, arg GetUserByPhoneAndTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneAndTenant, arg.Phone, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :one
UPDATE users
SET failed_login_attempts = COALESCE(failed_login_attempts, 0) + 1
WHERE id = $1
RETURNING id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementFailedLoginAttempts, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const listDriversByTenant = `-- name: ListDriversByTenant :many
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE tenant_id = $1 AND role = 'driver'
ORDER BY full_name
LIMIT $2 OFFSET $3
`

type ListDriversByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListDriversByTenant(ctx context.Context, arg ListDriversByTenantParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listDriversByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Role,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.PinHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.PasswordResetRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Role,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.PinHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.PasswordResetRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserAccount = `-- name: LockUserAccount :exec
UPDATE users
SET locked_until = $2
WHERE id = $1
`

type LockUserAccountParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	LockedUntil pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) error {
	_, err := q.db.Exec(ctx, lockUserAccount, arg.ID, arg.LockedUntil)
	return err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, id)
	return err
}

const unlockUserAccount = `-- name: UnlockUserAccount :exec
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) UnlockUserAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlockUserAccount, id)
	return err
}

const updatePIN = `-- name: UpdatePIN :one
UPDATE users
SET pin_hash = $2, failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
RETURNING id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required
`

type UpdatePINParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	PinHash *string     `db:"pin_hash" json:"pin_hash"`
}

func (q *Queries) UpdatePIN(ctx context.Context, arg UpdatePINParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePIN, arg.ID, arg.PinHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET password_hash = $2, password_reset_required = false, failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
RETURNING id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    full_name = COALESCE($3, full_name),
    phone = COALESCE($4, phone),
    email = COALESCE($5, email),
    password_hash = COALESCE($6, password_hash),
    pin_hash = COALESCE($7, pin_hash),
    is_active = COALESCE($8, is_active)
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, role, full_name, phone, email, password_hash, pin_hash, is_active, created_at, updated_at, failed_login_attempts, locked_until, password_reset_required
`

type UpdateUserParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	TenantID     pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	FullName     *string     `db:"full_name" json:"full_name"`
	Phone        *string     `db:"phone" json:"phone"`
	Email        *string     `db:"email" json:"email"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
	PinHash      *string     `db:"pin_hash" json:"pin_hash"`
	IsActive     *bool       `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.TenantID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.PinHash,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordResetRequired,
	)
	return i, err
}
