// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignDriverToShipment(ctx context.Context, arg AssignDriverToShipmentParams) (Shipment, error)
	CountDriversByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountShipmentsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountTrackingEventsByShipment(ctx context.Context, shipmentID pgtype.UUID) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CreatePOD(ctx context.Context, arg CreatePODParams) (ProofOfDelivery, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTrackingEvent(ctx context.Context, arg CreateTrackingEventParams) (TrackingEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetPODByShipmentID(ctx context.Context, arg GetPODByShipmentIDParams) (GetPODByShipmentIDRow, error)
	GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetShipmentByID(ctx context.Context, arg GetShipmentByIDParams) (Shipment, error)
	GetShipmentByTrackingNumber(ctx context.Context, trackingNumber string) (Shipment, error)
	GetShipmentsForSync(ctx context.Context, arg GetShipmentsForSyncParams) ([]Shipment, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTrackingEventsForSync(ctx context.Context, arg GetTrackingEventsForSyncParams) ([]GetTrackingEventsForSyncRow, error)
	GetUnsyncedPODs(ctx context.Context, arg GetUnsyncedPODsParams) ([]GetUnsyncedPODsRow, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByEmailAndTenant(ctx context.Context, arg GetUserByEmailAndTenantParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	GetUserByPhoneAndTenant(ctx context.Context, arg GetUserByPhoneAndTenantParams) (User, error)
	ListActiveShipmentsByDriver(ctx context.Context, arg ListActiveShipmentsByDriverParams) ([]Shipment, error)
	ListDriversByTenant(ctx context.Context, arg ListDriversByTenantParams) ([]User, error)
	ListShipmentsByDriver(ctx context.Context, arg ListShipmentsByDriverParams) ([]Shipment, error)
	ListShipmentsByStatus(ctx context.Context, arg ListShipmentsByStatusParams) ([]Shipment, error)
	ListShipmentsByTenant(ctx context.Context, arg ListShipmentsByTenantParams) ([]Shipment, error)
	ListTrackingEventsByDriver(ctx context.Context, arg ListTrackingEventsByDriverParams) ([]ListTrackingEventsByDriverRow, error)
	ListTrackingEventsByShipment(ctx context.Context, arg ListTrackingEventsByShipmentParams) ([]ListTrackingEventsByShipmentRow, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]User, error)
	MarkTrackingEventsSynced(ctx context.Context, dollar_1 []pgtype.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	SearchShipments(ctx context.Context, arg SearchShipmentsParams) ([]Shipment, error)
	UpdatePODSyncedAt(ctx context.Context, id pgtype.UUID) error
	UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (Shipment, error)
	UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
