// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTrackingEventsByShipment = `-- name: CountTrackingEventsByShipment :one
SELECT COUNT(*) FROM tracking_events WHERE shipment_id = $1
`

func (q *Queries) CountTrackingEventsByShipment(ctx context.Context, shipmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackingEventsByShipment, shipmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrackingEvent = `-- name: CreateTrackingEvent :one
INSERT INTO tracking_events (
    tenant_id, shipment_id, driver_id,
    coordinates, accuracy_meters, speed_kph, heading,
    event_type, status, note,
    recorded_at, device_id, battery_level
) VALUES (
    $1, $2, $3, ST_MakePoint($4, $5)::geometry(Point, 4326), $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, tenant_id, shipment_id, driver_id, coordinates, accuracy_meters, speed_kph, heading, event_type, status, note, recorded_at, synced_at, device_id, battery_level
`

type CreateTrackingEventParams struct {
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID     pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID       pgtype.UUID        `db:"driver_id" json:"driver_id"`
	StMakepoint    interface{}        `db:"st_makepoint" json:"st_makepoint"`
	StMakepoint_2  interface{}        `db:"st_makepoint_2" json:"st_makepoint_2"`
	AccuracyMeters pgtype.Numeric     `db:"accuracy_meters" json:"accuracy_meters"`
	SpeedKph       pgtype.Numeric     `db:"speed_kph" json:"speed_kph"`
	Heading        pgtype.Numeric     `db:"heading" json:"heading"`
	EventType      string             `db:"event_type" json:"event_type"`
	Status         *string            `db:"status" json:"status"`
	Note           *string            `db:"note" json:"note"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	DeviceID       *string            `db:"device_id" json:"device_id"`
	BatteryLevel   *int32             `db:"battery_level" json:"battery_level"`
}

func (q *Queries) CreateTrackingEvent(ctx context.Context, arg CreateTrackingEventParams) (TrackingEvent, error) {
	row := q.db.QueryRow(ctx, createTrackingEvent,
		arg.TenantID,
		arg.ShipmentID,
		arg.DriverID,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.AccuracyMeters,
		arg.SpeedKph,
		arg.Heading,
		arg.EventType,
		arg.Status,
		arg.Note,
		arg.RecordedAt,
		arg.DeviceID,
		arg.BatteryLevel,
	)
	var i TrackingEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentID,
		&i.DriverID,
		&i.Coordinates,
		&i.AccuracyMeters,
		&i.SpeedKph,
		&i.Heading,
		&i.EventType,
		&i.Status,
		&i.Note,
		&i.RecordedAt,
		&i.SyncedAt,
		&i.DeviceID,
		&i.BatteryLevel,
	)
	return i, err
}

const getTrackingEventsForSync = `-- name: GetTrackingEventsForSync :many
SELECT id, tenant_id, shipment_id, driver_id,
       ST_X(coordinates::geometry) as longitude,
       ST_Y(coordinates::geometry) as latitude,
       accuracy_meters, speed_kph, heading,
       event_type, status, note,
       recorded_at, synced_at, device_id, battery_level
FROM tracking_events
WHERE driver_id = $1
  AND tenant_id = $2
  AND recorded_at > $3
  AND synced_at IS NULL
ORDER BY recorded_at ASC
`

type GetTrackingEventsForSyncParams struct {
	DriverID   pgtype.UUID        `db:"driver_id" json:"driver_id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	RecordedAt pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type GetTrackingEventsForSyncRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID     pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID       pgtype.UUID        `db:"driver_id" json:"driver_id"`
	Longitude      interface{}        `db:"longitude" json:"longitude"`
	Latitude       interface{}        `db:"latitude" json:"latitude"`
	AccuracyMeters pgtype.Numeric     `db:"accuracy_meters" json:"accuracy_meters"`
	SpeedKph       pgtype.Numeric     `db:"speed_kph" json:"speed_kph"`
	Heading        pgtype.Numeric     `db:"heading" json:"heading"`
	EventType      string             `db:"event_type" json:"event_type"`
	Status         *string            `db:"status" json:"status"`
	Note           *string            `db:"note" json:"note"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt       pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
	DeviceID       *string            `db:"device_id" json:"device_id"`
	BatteryLevel   *int32             `db:"battery_level" json:"battery_level"`
}

func (q *Queries) GetTrackingEventsForSync(ctx context.Context, arg GetTrackingEventsForSyncParams) ([]GetTrackingEventsForSyncRow, error) {
	rows, err := q.db.Query(ctx, getTrackingEventsForSync, arg.DriverID, arg.TenantID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrackingEventsForSyncRow{}
	for rows.Next() {
		var i GetTrackingEventsForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShipmentID,
			&i.DriverID,
			&i.Longitude,
			&i.Latitude,
			&i.AccuracyMeters,
			&i.SpeedKph,
			&i.Heading,
			&i.EventType,
			&i.Status,
			&i.Note,
			&i.RecordedAt,
			&i.SyncedAt,
			&i.DeviceID,
			&i.BatteryLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingEventsByDriver = `-- name: ListTrackingEventsByDriver :many
SELECT id, tenant_id, shipment_id, driver_id,
       ST_X(coordinates::geometry) as longitude,
       ST_Y(coordinates::geometry) as latitude,
       accuracy_meters, speed_kph, heading,
       event_type, status, note,
       recorded_at, synced_at, device_id, battery_level
FROM tracking_events
WHERE driver_id = $1 AND tenant_id = $2
ORDER BY recorded_at DESC
LIMIT $3 OFFSET $4
`

type ListTrackingEventsByDriverParams struct {
	DriverID pgtype.UUID `db:"driver_id" json:"driver_id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

type ListTrackingEventsByDriverRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID     pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID       pgtype.UUID        `db:"driver_id" json:"driver_id"`
	Longitude      interface{}        `db:"longitude" json:"longitude"`
	Latitude       interface{}        `db:"latitude" json:"latitude"`
	AccuracyMeters pgtype.Numeric     `db:"accuracy_meters" json:"accuracy_meters"`
	SpeedKph       pgtype.Numeric     `db:"speed_kph" json:"speed_kph"`
	Heading        pgtype.Numeric     `db:"heading" json:"heading"`
	EventType      string             `db:"event_type" json:"event_type"`
	Status         *string            `db:"status" json:"status"`
	Note           *string            `db:"note" json:"note"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt       pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
	DeviceID       *string            `db:"device_id" json:"device_id"`
	BatteryLevel   *int32             `db:"battery_level" json:"battery_level"`
}

func (q *Queries) ListTrackingEventsByDriver(ctx context.Context, arg ListTrackingEventsByDriverParams) ([]ListTrackingEventsByDriverRow, error) {
	rows, err := q.db.Query(ctx, listTrackingEventsByDriver,
		arg.DriverID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackingEventsByDriverRow{}
	for rows.Next() {
		var i ListTrackingEventsByDriverRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShipmentID,
			&i.DriverID,
			&i.Longitude,
			&i.Latitude,
			&i.AccuracyMeters,
			&i.SpeedKph,
			&i.Heading,
			&i.EventType,
			&i.Status,
			&i.Note,
			&i.RecordedAt,
			&i.SyncedAt,
			&i.DeviceID,
			&i.BatteryLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingEventsByShipment = `-- name: ListTrackingEventsByShipment :many
SELECT id, tenant_id, shipment_id, driver_id,
       ST_X(coordinates::geometry) as longitude,
       ST_Y(coordinates::geometry) as latitude,
       accuracy_meters, speed_kph, heading,
       event_type, status, note,
       recorded_at, synced_at, device_id, battery_level
FROM tracking_events
WHERE shipment_id = $1 AND tenant_id = $2
ORDER BY recorded_at DESC
LIMIT $3 OFFSET $4
`

type ListTrackingEventsByShipmentParams struct {
	ShipmentID pgtype.UUID `db:"shipment_id" json:"shipment_id"`
	TenantID   pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type ListTrackingEventsByShipmentRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ShipmentID     pgtype.UUID        `db:"shipment_id" json:"shipment_id"`
	DriverID       pgtype.UUID        `db:"driver_id" json:"driver_id"`
	Longitude      interface{}        `db:"longitude" json:"longitude"`
	Latitude       interface{}        `db:"latitude" json:"latitude"`
	AccuracyMeters pgtype.Numeric     `db:"accuracy_meters" json:"accuracy_meters"`
	SpeedKph       pgtype.Numeric     `db:"speed_kph" json:"speed_kph"`
	Heading        pgtype.Numeric     `db:"heading" json:"heading"`
	EventType      string             `db:"event_type" json:"event_type"`
	Status         *string            `db:"status" json:"status"`
	Note           *string            `db:"note" json:"note"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SyncedAt       pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
	DeviceID       *string            `db:"device_id" json:"device_id"`
	BatteryLevel   *int32             `db:"battery_level" json:"battery_level"`
}

func (q *Queries) ListTrackingEventsByShipment(ctx context.Context, arg ListTrackingEventsByShipmentParams) ([]ListTrackingEventsByShipmentRow, error) {
	rows, err := q.db.Query(ctx, listTrackingEventsByShipment,
		arg.ShipmentID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackingEventsByShipmentRow{}
	for rows.Next() {
		var i ListTrackingEventsByShipmentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShipmentID,
			&i.DriverID,
			&i.Longitude,
			&i.Latitude,
			&i.AccuracyMeters,
			&i.SpeedKph,
			&i.Heading,
			&i.EventType,
			&i.Status,
			&i.Note,
			&i.RecordedAt,
			&i.SyncedAt,
			&i.DeviceID,
			&i.BatteryLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTrackingEventsSynced = `-- name: MarkTrackingEventsSynced :exec
UPDATE tracking_events
SET synced_at = NOW()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkTrackingEventsSynced(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTrackingEventsSynced, dollar_1)
	return err
}
