// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVehiclesByTenant = `-- name: CountVehiclesByTenant :one
SELECT COUNT(*) FROM vehicles WHERE tenant_id = $1 AND is_active = true
`

func (q *Queries) CountVehiclesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVehiclesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
    tenant_id, plate_number, vehicle_type, is_active
) VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, plate_number, vehicle_type, is_active, created_at, updated_at
`

type CreateVehicleParams struct {
	TenantID    pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	PlateNumber string      `db:"plate_number" json:"plate_number"`
	VehicleType *string     `db:"vehicle_type" json:"vehicle_type"`
	IsActive    *bool       `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.TenantID,
		arg.PlateNumber,
		arg.VehicleType,
		arg.IsActive,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlateNumber,
		&i.VehicleType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
UPDATE vehicles
SET is_active = false
WHERE id = $1 AND tenant_id = $2
`

type DeleteVehicleParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) error {
	_, err := q.db.Exec(ctx, deleteVehicle, arg.ID, arg.TenantID)
	return err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, tenant_id, plate_number, vehicle_type, is_active, created_at, updated_at FROM vehicles
WHERE id = $1 AND tenant_id = $2
`

type GetVehicleByIDParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetVehicleByID(ctx context.Context, arg GetVehicleByIDParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, arg.ID, arg.TenantID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlateNumber,
		&i.VehicleType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteVehicle = `-- name: HardDeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1 AND tenant_id = $2
`

type HardDeleteVehicleParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) HardDeleteVehicle(ctx context.Context, arg HardDeleteVehicleParams) error {
	_, err := q.db.Exec(ctx, hardDeleteVehicle, arg.ID, arg.TenantID)
	return err
}

const listActiveVehiclesByTenant = `-- name: ListActiveVehiclesByTenant :many
SELECT id, tenant_id, plate_number, vehicle_type, is_active, created_at, updated_at FROM vehicles
WHERE tenant_id = $1 AND is_active = true
ORDER BY plate_number
`

func (q *Queries) ListActiveVehiclesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listActiveVehiclesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlateNumber,
			&i.VehicleType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByTenant = `-- name: ListVehiclesByTenant :many
SELECT id, tenant_id, plate_number, vehicle_type, is_active, created_at, updated_at FROM vehicles
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVehiclesByTenantParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListVehiclesByTenant(ctx context.Context, arg ListVehiclesByTenantParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlateNumber,
			&i.VehicleType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET
    plate_number = COALESCE($3, plate_number),
    vehicle_type = COALESCE($4, vehicle_type),
    is_active = COALESCE($5, is_active)
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, plate_number, vehicle_type, is_active, created_at, updated_at
`

type UpdateVehicleParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	TenantID    pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	PlateNumber *string     `db:"plate_number" json:"plate_number"`
	VehicleType *string     `db:"vehicle_type" json:"vehicle_type"`
	IsActive    *bool       `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.TenantID,
		arg.PlateNumber,
		arg.VehicleType,
		arg.IsActive,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlateNumber,
		&i.VehicleType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
